//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReniecService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReniecService.serviciomqSoap")]
    public interface serviciomqSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerDatosBasicos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReniecService.obtenerDatosBasicosResponse> obtenerDatosBasicosAsync(ReniecService.obtenerDatosBasicosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerDatosCompletos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReniecService.obtenerDatosCompletosResponse> obtenerDatosCompletosAsync(ReniecService.obtenerDatosCompletosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Credencialmq
    {
        
        private string appField;
        
        private string usuarioField;
        
        private string claveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string app
        {
            get
            {
                return this.appField;
            }
            set
            {
                this.appField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosBasicos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerDatosBasicosRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ReniecService.Credencialmq Credencialmq;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nrodoc;
        
        public obtenerDatosBasicosRequest()
        {
        }
        
        public obtenerDatosBasicosRequest(ReniecService.Credencialmq Credencialmq, string nrodoc)
        {
            this.Credencialmq = Credencialmq;
            this.nrodoc = nrodoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosBasicosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerDatosBasicosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] obtenerDatosBasicosResult;
        
        public obtenerDatosBasicosResponse()
        {
        }
        
        public obtenerDatosBasicosResponse(string[] obtenerDatosBasicosResult)
        {
            this.obtenerDatosBasicosResult = obtenerDatosBasicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosCompletos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerDatosCompletosRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ReniecService.Credencialmq Credencialmq;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nrodoc;
        
        public obtenerDatosCompletosRequest()
        {
        }
        
        public obtenerDatosCompletosRequest(ReniecService.Credencialmq Credencialmq, string nrodoc)
        {
            this.Credencialmq = Credencialmq;
            this.nrodoc = nrodoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosCompletosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerDatosCompletosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] obtenerDatosCompletosResult;
        
        public obtenerDatosCompletosResponse()
        {
        }
        
        public obtenerDatosCompletosResponse(string[] obtenerDatosCompletosResult)
        {
            this.obtenerDatosCompletosResult = obtenerDatosCompletosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface serviciomqSoapChannel : ReniecService.serviciomqSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class serviciomqSoapClient : System.ServiceModel.ClientBase<ReniecService.serviciomqSoap>, ReniecService.serviciomqSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public serviciomqSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(serviciomqSoapClient.GetBindingForEndpoint(endpointConfiguration), serviciomqSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviciomqSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(serviciomqSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviciomqSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(serviciomqSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviciomqSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReniecService.obtenerDatosBasicosResponse> ReniecService.serviciomqSoap.obtenerDatosBasicosAsync(ReniecService.obtenerDatosBasicosRequest request)
        {
            return base.Channel.obtenerDatosBasicosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReniecService.obtenerDatosBasicosResponse> obtenerDatosBasicosAsync(ReniecService.Credencialmq Credencialmq, string nrodoc)
        {
            ReniecService.obtenerDatosBasicosRequest inValue = new ReniecService.obtenerDatosBasicosRequest();
            inValue.Credencialmq = Credencialmq;
            inValue.nrodoc = nrodoc;
            return ((ReniecService.serviciomqSoap)(this)).obtenerDatosBasicosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReniecService.obtenerDatosCompletosResponse> ReniecService.serviciomqSoap.obtenerDatosCompletosAsync(ReniecService.obtenerDatosCompletosRequest request)
        {
            return base.Channel.obtenerDatosCompletosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReniecService.obtenerDatosCompletosResponse> obtenerDatosCompletosAsync(ReniecService.Credencialmq Credencialmq, string nrodoc)
        {
            ReniecService.obtenerDatosCompletosRequest inValue = new ReniecService.obtenerDatosCompletosRequest();
            inValue.Credencialmq = Credencialmq;
            inValue.nrodoc = nrodoc;
            return ((ReniecService.serviciomqSoap)(this)).obtenerDatosCompletosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.serviciomqSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.serviciomqSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.serviciomqSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://wsvmin.minsa.gob.pe/wsreniecmq/serviciomq.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.serviciomqSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://wsvmin.minsa.gob.pe/wsreniecmq/serviciomq.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            serviciomqSoap,
            
            serviciomqSoap12,
        }
    }
}
